package model;
// default package
// Generated 2018/10/8 �W�� 09:30:49 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Certificationitem generated by hbm2java
 */
@Entity
@Table(name = "certificationitem", catalog = "mfg_world")
public class CertificationItemBean implements java.io.Serializable {

	private Integer id;
	private String area;
	private String knowledge;
	private String technical;
	private String training;
	private Byte trainingOnly;

	public CertificationItemBean() {
	}

	public CertificationItemBean(String area, String knowledge, String technical, String training, Byte trainingOnly) {
		this.area = area;
		this.knowledge = knowledge;
		this.technical = technical;
		this.training = training;
		this.trainingOnly = trainingOnly;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "area", length = 10)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "knowledge", length = 20)
	public String getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(String knowledge) {
		this.knowledge = knowledge;
	}

	@Column(name = "technical", length = 20)
	public String getTechnical() {
		return this.technical;
	}

	public void setTechnical(String technical) {
		this.technical = technical;
	}

	@Column(name = "training", length = 20)
	public String getTraining() {
		return this.training;
	}

	public void setTraining(String training) {
		this.training = training;
	}

	@Column(name = "training_only")
	public Byte getTrainingOnly() {
		return this.trainingOnly;
	}

	public void setTrainingOnly(Byte trainingOnly) {
		this.trainingOnly = trainingOnly;
	}

	@Override
	public String toString() {
		return "CertificationItemBean [id=" + id + ", area=" + area + ", knowledge=" + knowledge + ", technical="
				+ technical + ", training=" + training + ", trainingOnly=" + trainingOnly + "]";
	}
	
	

}
