package model;
// default package
// Generated 2018/8/10 �U�� 02:34:36 by Hibernate Tools 5.1.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClassInfo generated by hbm2java
 */
@Entity
@Table(name = "class_info", catalog = "mfg_world")
public class ClassInfoBean implements java.io.Serializable {

	private Integer id;
	private String level;
	private String grade;
	private String className;

	public ClassInfoBean() {
	}

	public ClassInfoBean(String level, String grade, String className) {
		this.level = level;
		this.grade = grade;
		this.className = className;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "level", length = 1)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "grade", length = 1)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "class_name", length = 20)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Override
	public String toString() {
		return "ClassInfoBean [id=" + id + ", level=" + level + ", grade=" + grade + ", className=" + className + "]";
	}
	
	

}
