package model;
// default package
// Generated 2018/8/14 �W�� 10:17:46 by Hibernate Tools 5.1.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HumanInfo generated by hbm2java
 */
@Entity
@Table(name = "human_info", catalog = "mfg_world")
public class HumanInfoBean implements java.io.Serializable {

	private Integer id;
	private String workNum;
	private String account;
	private String password;
	private String name;
	private String sex;
	private Date dutyDate;
	private Date resignationDate;
	private Integer grade;
	private String class_;
	private String area;
	private String email;
	private String permission;
	private Date birthday;
	private String tel;
	private String contactPersion;
	private String contactPersionTel;
	private String address;
	private String dormitory;

	public HumanInfoBean() {
	}

	public HumanInfoBean(String workNum, String account, String password, String name, String sex, Date dutyDate,
			Date resignationDate, Integer grade, String class_, String area, String email, String permission,
			Date birthday, String tel, String contactPersion, String contactPersionTel, String address,
			String dormitory) {
		this.workNum = workNum;
		this.account = account;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.dutyDate = dutyDate;
		this.resignationDate = resignationDate;
		this.grade = grade;
		this.class_ = class_;
		this.area = area;
		this.email = email;
		this.permission = permission;
		this.birthday = birthday;
		this.tel = tel;
		this.contactPersion = contactPersion;
		this.contactPersionTel = contactPersionTel;
		this.address = address;
		this.dormitory = dormitory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "work_num", length = 6)
	public String getWorkNum() {
		return this.workNum;
	}

	public void setWorkNum(String workNum) {
		this.workNum = workNum;
	}

	@Column(name = "account", length = 15)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 6)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "duty_date", length = 10)
	public Date getDutyDate() {
		return this.dutyDate;
	}

	public void setDutyDate(Date dutyDate) {
		this.dutyDate = dutyDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resignation_date", length = 10)
	public Date getResignationDate() {
		return this.resignationDate;
	}

	public void setResignationDate(Date resignationDate) {
		this.resignationDate = resignationDate;
	}

	@Column(name = "grade")
	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	@Column(name = "class", length = 3)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "area", length = 10)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "permission", length = 5)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "contact_persion", length = 45)
	public String getContactPersion() {
		return this.contactPersion;
	}

	public void setContactPersion(String contactPersion) {
		this.contactPersion = contactPersion;
	}

	@Column(name = "contact_persion_tel", length = 45)
	public String getContactPersionTel() {
		return this.contactPersionTel;
	}

	public void setContactPersionTel(String contactPersionTel) {
		this.contactPersionTel = contactPersionTel;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "dormitory", length = 4)
	public String getDormitory() {
		return this.dormitory;
	}

	public void setDormitory(String dormitory) {
		this.dormitory = dormitory;
	}

	@Override
	public String toString() {
		return "HumanInfoBean [id=" + id + ", workNum=" + workNum + ", account=" + account + ", password=" + password
				+ ", name=" + name + ", sex=" + sex + ", dutyDate=" + dutyDate + ", resignationDate=" + resignationDate
				+ ", grade=" + grade + ", class_=" + class_ + ", area=" + area + ", email=" + email + ", permission="
				+ permission + ", birthday=" + birthday + ", tel=" + tel + ", contactPersion=" + contactPersion
				+ ", contactPersionTel=" + contactPersionTel + ", address=" + address + ", dormitory=" + dormitory
				+ "]";
	}

	
}
