package model;
// default package
// Generated 2019/3/5 �W�� 11:58:42 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackageInfo generated by hbm2java
 */
@Entity
@Table(name = "package_info", catalog = "mfg_world")
public class PackageInfoBean implements java.io.Serializable {

	private Integer id;
	private Date date1;
	private Date time1;
	private String reactorLot;
	private String box;
	private String product;
	private String lot1;
	private float weight1;
	private String lot2;
	private float weight2;
	private String lot3;
	private float weight3;
	private float totalWeight;
	private String recorder;
	private String reactorLot2;
	private String reactorLot3;
	private boolean pullerUse;
	private String memo;

	public PackageInfoBean() {
	}

	public PackageInfoBean(Date date1, Date time1, String reactorLot, String box, String product, String lot1,
			float weight1, String lot2, float weight2, String lot3, float weight3, float totalWeight, String recorder,
			boolean pullerUse, String memo) {
		this.date1 = date1;
		this.time1 = time1;
		this.reactorLot = reactorLot;
		this.box = box;
		this.product = product;
		this.lot1 = lot1;
		this.weight1 = weight1;
		this.lot2 = lot2;
		this.weight2 = weight2;
		this.lot3 = lot3;
		this.weight3 = weight3;
		this.totalWeight = totalWeight;
		this.recorder = recorder;
		this.pullerUse = pullerUse;
		this.memo = memo;
	}

	public PackageInfoBean(Date date1, Date time1, String reactorLot, String box, String product, String lot1,
			float weight1, String lot2, float weight2, String lot3, float weight3, float totalWeight, String recorder,
			String reactorLot2, String reactorLot3, boolean pullerUse, String memo) {
		this.date1 = date1;
		this.time1 = time1;
		this.reactorLot = reactorLot;
		this.box = box;
		this.product = product;
		this.lot1 = lot1;
		this.weight1 = weight1;
		this.lot2 = lot2;
		this.weight2 = weight2;
		this.lot3 = lot3;
		this.weight3 = weight3;
		this.totalWeight = totalWeight;
		this.recorder = recorder;
		this.reactorLot2 = reactorLot2;
		this.reactorLot3 = reactorLot3;
		this.pullerUse = pullerUse;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date1", nullable = false, length = 10)
	public Date getDate1() {
		return this.date1;
	}

	public void setDate1(Date date1) {
		this.date1 = date1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time1", nullable = false, length = 8)
	public Date getTime1() {
		return this.time1;
	}

	public void setTime1(Date time1) {
		this.time1 = time1;
	}

	@Column(name = "reactor_lot", nullable = false, length = 20)
	public String getReactorLot() {
		return this.reactorLot;
	}

	public void setReactorLot(String reactorLot) {
		this.reactorLot = reactorLot;
	}

	@Column(name = "box", nullable = false, length = 65535)
	public String getBox() {
		return this.box;
	}

	public void setBox(String box) {
		this.box = box;
	}

	@Column(name = "product", nullable = false, length = 65535)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "lot1", nullable = false, length = 65535)
	public String getLot1() {
		return this.lot1;
	}

	public void setLot1(String lot1) {
		this.lot1 = lot1;
	}

	@Column(name = "weight1", nullable = false, precision = 12, scale = 0)
	public float getWeight1() {
		return this.weight1;
	}

	public void setWeight1(float weight1) {
		this.weight1 = weight1;
	}

	@Column(name = "lot2", nullable = false, length = 65535)
	public String getLot2() {
		return this.lot2;
	}

	public void setLot2(String lot2) {
		this.lot2 = lot2;
	}

	@Column(name = "weight2", nullable = false, precision = 12, scale = 0)
	public float getWeight2() {
		return this.weight2;
	}

	public void setWeight2(float weight2) {
		this.weight2 = weight2;
	}

	@Column(name = "lot3", nullable = false, length = 65535)
	public String getLot3() {
		return this.lot3;
	}

	public void setLot3(String lot3) {
		this.lot3 = lot3;
	}

	@Column(name = "weight3", nullable = false, precision = 12, scale = 0)
	public float getWeight3() {
		return this.weight3;
	}

	public void setWeight3(float weight3) {
		this.weight3 = weight3;
	}

	@Column(name = "total_weight", nullable = false, precision = 12, scale = 0)
	public float getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(float totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "recorder", nullable = false, length = 65535)
	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	@Column(name = "reactor_lot2", length = 20)
	public String getReactorLot2() {
		return this.reactorLot2;
	}

	public void setReactorLot2(String reactorLot2) {
		this.reactorLot2 = reactorLot2;
	}

	@Column(name = "reactor_lot3", length = 20)
	public String getReactorLot3() {
		return this.reactorLot3;
	}

	public void setReactorLot3(String reactorLot3) {
		this.reactorLot3 = reactorLot3;
	}

	@Column(name = "puller_use" )
	public boolean isPullerUse() {
		return this.pullerUse;
	}

	public void setPullerUse(boolean pullerUse) {
		this.pullerUse = pullerUse;
	}

	@Column(name = "memo", length = 65535)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Override
	public String toString() {
		return "PackageInfo [id=" + id + ", date1=" + date1 + ", time1=" + time1 + ", reactorLot=" + reactorLot
				+ ", box=" + box + ", product=" + product + ", lot1=" + lot1 + ", weight1=" + weight1 + ", lot2=" + lot2
				+ ", weight2=" + weight2 + ", lot3=" + lot3 + ", weight3=" + weight3 + ", totalWeight=" + totalWeight
				+ ", recorder=" + recorder + ", reactorLot2=" + reactorLot2 + ", reactorLot3=" + reactorLot3
				+ ", pullerUse=" + pullerUse + ", memo=" + memo + "]";
	}

}
