package model;
// default package
// Generated 2018/10/12 �U�� 02:37:41 by Hibernate Tools 5.0.6.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonCertificationInfo generated by hbm2java
 */
@Entity
@Table(name = "person_certification_info", catalog = "mfg_world")
public class PersonCertificationInfoBean implements java.io.Serializable {

	private Integer id;
	private String workNum;
	private String name;
	private String area;
	private String shift;
	private String knowledge;
	private String technical;
	private String training;
	private Byte trainingOnly;
//	private Set<PersonCertificationRecordBean> personCertificationRecords = new HashSet<PersonCertificationRecordBean>(0);
	private List<PersonCertificationRecordBean> personCertificationRecords = new ArrayList();
	public PersonCertificationInfoBean() {
	}

	public PersonCertificationInfoBean(String workNum, String name, String area, String shift, String knowledge,
			String technical, String training, Byte trainingOnly,
			List<PersonCertificationRecordBean> personCertificationRecords) {
		this.workNum = workNum;
		this.name = name;
		this.area = area;
		this.shift = shift;
		this.knowledge = knowledge;
		this.technical = technical;
		this.training = training;
		this.trainingOnly = trainingOnly;
		this.personCertificationRecords = personCertificationRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "work_num", length = 5)
	public String getWorkNum() {
		return this.workNum;
	}

	public void setWorkNum(String workNum) {
		this.workNum = workNum;
	}

	@Column(name = "name", length = 6)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "area", length = 20)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "shift", length = 3)
	public String getShift() {
		return this.shift;
	}

	public void setShift(String shift) {
		this.shift = shift;
	}

	@Column(name = "knowledge", length = 45)
	public String getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(String knowledge) {
		this.knowledge = knowledge;
	}

	@Column(name = "technical", length = 45)
	public String getTechnical() {
		return this.technical;
	}

	public void setTechnical(String technical) {
		this.technical = technical;
	}

	@Column(name = "training", length = 20)
	public String getTraining() {
		return this.training;
	}

	public void setTraining(String training) {
		this.training = training;
	}

	@Column(name = "training_only")
	public Byte getTrainingOnly() {
		return this.trainingOnly;
	}

	public void setTrainingOnly(Byte trainingOnly) {
		this.trainingOnly = trainingOnly;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personCertificationInfo")
	public List<PersonCertificationRecordBean> getPersonCertificationRecords() {
		return this.personCertificationRecords;
	}

	public void setPersonCertificationRecords(List<PersonCertificationRecordBean> personCertificationRecords) {
		this.personCertificationRecords = personCertificationRecords;
	}

	@Override
	public String toString() {
		return "PersonCertificationInfoBean [id=" + id + ", workNum=" + workNum + ", name=" + name + ", area=" + area
				+ ", shift=" + shift + ", knowledge=" + knowledge + ", technical=" + technical + ", training="
				+ training + ", trainingOnly=" + trainingOnly + ", personCertificationRecords=***]";
		}

}
