package model;
// default package
// Generated 2018/10/12 �U�� 02:37:41 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.OrderBy;

/**
 * PersonCertificationRecord generated by hbm2java
 */
@Entity
@Table(name = "person_certification_record", catalog = "mfg_world")
public class PersonCertificationRecordBean implements java.io.Serializable {

	private Integer id;
	private PersonCertificationInfoBean personCertificationInfo;
	private Date knowledgeDate;
	private Integer knowledgeScore;
	private Date technicalDate;
	private Integer technicalScore;
	private Date trainingDate;
	private String trainer;

	public PersonCertificationRecordBean() {
	}

	public PersonCertificationRecordBean(PersonCertificationInfoBean personCertificationInfo, Date knowledgeDate,
			Integer knowledgeScore, Date technicalDate, Integer technicalScore
			, Date trainingDate,String trainer) {
		this.personCertificationInfo = personCertificationInfo;
		this.knowledgeDate = knowledgeDate;
		this.knowledgeScore = knowledgeScore;
		this.technicalDate = technicalDate;
		this.technicalScore = technicalScore;
		this.trainingDate = trainingDate;
		this.trainer = trainer ;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_certification_id")
 	public PersonCertificationInfoBean getPersonCertificationInfo() {
		return this.personCertificationInfo;
	}

	public void setPersonCertificationInfo(PersonCertificationInfoBean personCertificationInfo) {
		this.personCertificationInfo = personCertificationInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "knowledge_date", length = 10)
	public Date getKnowledgeDate() {
		return this.knowledgeDate;
	}

	public void setKnowledgeDate(Date knowledgeDate) {
		this.knowledgeDate = knowledgeDate;
	}

	@Column(name = "knowledge_score")
	public Integer getKnowledgeScore() {
		return this.knowledgeScore;
	}

	public void setKnowledgeScore(Integer knowledgeScore) {
		this.knowledgeScore = knowledgeScore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "technical_date", length = 10)
	public Date getTechnicalDate() {
		return this.technicalDate;
	}

	public void setTechnicalDate(Date technicalDate) {
		this.technicalDate = technicalDate;
	}

	@Column(name = "technical_score")
	public Integer getTechnicalScore() {
		return this.technicalScore;
	}

	public void setTechnicalScore(Integer technicalScore) {
		this.technicalScore = technicalScore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_date", length = 10)
	public Date getTrainingDate() {
		return this.trainingDate;
	}

	public void setTrainingDate(Date trainingDate) {
		this.trainingDate = trainingDate;
	}

	
	@Column(name = "trainer" ,length = 6)
	public String getTrainer() {
		return this.trainer;
	}
	
	public void setTrainer(String trainer) {
		this.trainer = trainer ; 
	}

	@Override
	public String toString() {
		return "PersonCertificationRecordBean [id=" + id + ", personCertificationInfo=" + personCertificationInfo
				+ ", knowledgeDate=" + knowledgeDate + ", knowledgeScore=" + knowledgeScore + ", technicalDate="
				+ technicalDate + ", technicalScore=" + technicalScore + ", trainingDate=" + trainingDate + ", trainer="
				+ trainer + "]";
	}
	
	
	
}
